services:
  app:
    build: .
    container_name: laravel-app
    restart: always
    volumes:
      - ./test-recipes:/var/www
    env_file:
      - ./test-recipes/.env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./test-recipes:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./test-recipes/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_recipes
    # Modify to prevent conflict with local database, should be 5432 for postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data: 